### ISSUE TITLE
Broken external file support

### ISSUE THREAD

**Issue by sadgmbh** [rmrevin/yii2-minify-view#10]
Currently, external files weren't be ignored by the $schema array from line 43.
In my case the process failes on line 122: `$content = file_get_contents(\Yii::getAlias($this->base_path) . $file);` while trying to include an external file using `//` shema in asset:
`file_get_contents(/var/www/[..]/dev/web///fonts.googleapis.com/css?family=Exo+2:400,600,800): failed to open stream: No such file or directory`

**Comment by rmrevin** [comment]
Fixed in version 1.7.6
