### ISSUE TITLE
Ошибка с расширением imperavi-widget

### ISSUE THREAD

**Issue by Temorfeouz** [rmrevin/yii2-minify-view#11]
Добрый день! Проблема с расширением https://github.com/vova07/yii2-imperavi-widget(оно работает нормально)
Проблема в том, что Ваше расширение пытается получить доступ к несуществующему файлу,
и выбрасывает исключение sha1_file(.../46523e8f/lang/en.js): failed to open stream: No such file or directory
в строке 341, 
там выполняется код $result .= sha1_file(\Yii::getAlias($this->base_path) . $file);

Проблему решит добавление проверки на существование файла, перед его использованием

Форкнуть и исправить - решение, но неохота дубликаты плодить))

**Comment by rmrevin** [comment]
Добрый день.
Просто не нужно подключать несуществующи
