### ISSUE TITLE
Path incorrect in Advanced Template

### ISSUE THREAD

**Issue by adiramardiani** [rmrevin/yii2-minify-view#13]
I use advanced application template with separate in backend and frontend, but give error `file_get_contents(C:\xampp\htdocs\dashboard/backend/web/dashboard/admin/assets/3b75345a/css/bootstrap.css): failed to open stream: No such file or directory`

```php
'view' => [
            'class' => '\rmrevin\yii\minify\View',
            'enableMinify' => true,
            'base_path' => '@backend/web', // path alias to web base
            'minify_path' => '@backend/web/minify', // path alias to save minify result
            'js_position' => [ \yii\web\View::POS_END ], // positions of js files to be minified
            'force_charset' => 'UTF-8', // charset forcibly assign, otherwise will use all of the files found charset
            'expand_imports' => true, // whether to change @import on content
        ]
```

I use `@app/web` or `@web` still give the wrong output path

**Comment by rmrevin** [comment]
Show your aliases.
```php
VarDumper::dump(\Yii::$aliases)
```

**Comment by adiramardiani** [comment]
```php
["@common"]=>
  string(32) "C:\xampp\htdocs\dashboard\common"
  ["@frontend"]=>
  string(34) "C:\xampp\htdocs\dashboard/frontend"
  ["@backend"]=>
  string(33) "C:\xampp\htdocs\dashboard/backend"
  ["@console"]=>
  string(33) "C:\xampp\htdocs\dashboard/console"
  ["@app"]=>
  string(33) "C:\xampp\htdocs\dashboard\backend"
  ["@vendor"]=>
  string(40) "C:\xampp\htdocs\dashboard/../yii2/vendor"
  ["@bower"]=>
  string(46) "C:\xampp\htdocs\dashboard/../yii2/vendor\bower"
  ["@npm"]=>
  string(44) "C:\xampp\htdocs\dashboard/../yii2/vendor\npm"
  ["@runtime"]=>
  string(41) "C:\xampp\htdocs\dashboard\backend\runtime"
  ["@webroot"]=>
  string(37) "C:/xampp/htdocs/dashboard/backend/web"
  ["@web"]=>
  string(16) "/dashboard/admin"
```

**Comment by rmrevin** [comment]
What path should be specified in the function "file_get_contents"?

**Comment by adiramardiani** [comment]
I think the alias show true output, but why show  error `file_get_contents(C:\xampp\htdocs\dashboard/backend/web/dashboard/admin/assets/3b75345a/css/bootstrap.css)`
the `/dashboard/admin/` is repeat again

**Comment by rmrevin** [comment]
`/dashboard/admin/` its controller? or path to `/dashboard/admin/index.php`?

**Comment by adiramardiani** [comment]
I use htaccess to hide frontend and backend folder with htaccess following this [link](http://www.yiiframework.com/wiki/755/how-to-hide-frontend-web-in-url-addresses-on-apache/)

For frontend as root domain, and backend with `admin` url, whether it be affects ?

**Comment by adiramardiani** [comment]
With normal url is
`http://localhost/dashboard/backend/web` and know with htaccess is `http://localhost/dashboard/admin`

**Comment by rmrevin** [comment]
This is normal. Answer the previous question please.
Url for frontend `http://localhost/`
Url for backend `http://localhost/dashboard/admin/`
?

**Comment by adiramardiani** [comment]
No, 
Url for frontend `http://localhost/dashboard`
Url for backend `http://localhost/dashboard/admin/`

Dashboard is my application name

**Comment by rmrevin** [comment]
Try the next solution. 
1. In the application config, fill attribute `[defaultRoute](https://github.com/yiisoft/yii2/blob/master/framework/web/Application.php#L28)`.
2. Alias `@web` set `/dashboard`.

**Comment by rmrevin** [comment]
I think we understood what a mistake. Seconds.

**Comment by adiramardiani** [comment]
What the mistake ?

**Comment by rmrevin** [comment]
Please copy the full error trace.

**Comment by adiramardiani** [comment]
![download](https://cloud.githubusercontent.com/assets/8703419/7586652/4582d3f6-f8d9-11e4-97ee-598f8042f387.png)

**Comment by rmrevin** [comment]
In `basePath` currently `@web`?
Must be `@backend/web`

**Comment by adiramardiani** [comment]
I use `@app/web` or `@web` or `@backend/web` still give the wrong output path

**Comment by rmrevin** [comment]
Show your `AssetBundle`, which connects bootstrap. Such an error is detected by using `baseUrl` in `AssetBundle`.
And show config `AssetManager`.

**Comment by adiramardiani** [comment]
```php
namespace backend\assets;
use yii\web\AssetBundle;
class BootstrapAsset extends AssetBundle{
    public $sourcePath = '@bower/bootstrap/dist';
    public $css = [
        'css/bootstrap.css',
    ];
	public $js = [
        'js/bootstrap.js',
    ];
}
```

**Comment by rmrevin** [comment]
And show config `AssetManager`.

**Comment by adiramardiani** [comment]
I'm not configure a `assetManager`

**Comment by adiramardiani** [comment]
For now I do not activate Minify 
```php
'view' => [
            'class' => '\rmrevin\yii\minify\View',
            'enableMinify' => false,
			'compress_output'=>true
        ]
```
Html compress is working well, but why are all my ajax page do not work, like GridView pagination etc ?

**Comment by rmrevin** [comment]
You can grant access to the code? Since we can not diagnose the problem remotely. We need to see how to configure the application.

**Comment by adiramardiani** [comment]
I use `web_path` and minify working well now, thanks :)
My configure like in your readme file
But why are all my ajax page do not work after compressed html page, like GridView pagination etc ?

**Comment by rmrevin** [comment]
You use pjax?

**Comment by adiramardiani** [comment]
Yes of course

**Comment by rmrevin** [comment]
Try using version 1.8.1

**Comment by adiramardiani** [comment]
version for what ?
pjax or ?

**Comment by rmrevin** [comment]
yii2-minify-view

**Comment by adiramardiani** [comment]
Now it working well :)
Sorry could not pull request or any others, I was very stupid :p
Can only give advice or enhancement, not about technical

Thank you so much

Closed :)

**Comment by rmrevin** [comment]
I'm glad I could help!
Good luck.
