### ISSUE TITLE
option parameter : minify js+css / only js / only css

### ISSUE THREAD

**Issue by mzysk** [rmrevin/yii2-minify-view#15]
I'm new to github, so forgive if my request is in wrong category.

Great extensions but minifying css causing conflicts in my case. Could you add parameter to decide if i want to minify js&css or just separate files?

For now i've just commented out #102 line of View.php and it's working good but want to have that solution updateable.

It will be great. Thank You.

**Comment by rmrevin** [comment]
Fixed in version 1.8.3.
Use parameters [`minifyCss`](https://github.com/rmrevin/yii2-minify-view/blob/master/View.php#L22) and [`minifyJs`](https://github.com/rmrevin/yii2-minify-view/blob/master/View.php#L25).
Thanks.
