### ISSUE TITLE
Минификатор срабатывает каждый раз при аякс запросе

### ISSUE THREAD

**Issue by RsD0p9BK** [rmrevin/yii2-minify-view#22]
Минификатор срабатывает каждый раз при аякс запросе. Получается что каждый запрос генерируется js файл в папке minify.
- в контроллере используется $this->renderPartial
- бандл подключается только в шапке
- папка web/assets очищена

upd.  если используется POS_HEAD, то проблемы не возникает

**Comment by rmrevin** [comment]
Accepted.

**Comment by RsD0p9BK** [comment]
Как временное решенеие изменил 122 строчку  в файле View.php:
```
self::PH_BODY_END => ($ajaxMode) ? "" : $this->renderBodyEndHtml($ajaxMode)
```

**Comment by rmrevin** [comment]
Внутри render partial подключаются какие-то assets?

**Comment by RsD0p9BK** [comment]
Нет, только в хедере. Но после того как запрос ушел генерируется JS с другим (меньшим) размером.

**Comment by rmrevin** [comment]
На каждый запрос генерируется? Или только один раз?
Особенность этого расширения в том, что оно минифицирует любой набод assets. То есть если в каком-то разделе помимо условного `AppAssetBundle` подключаются какие-то ещё assets, то он минифицирует это в новый пак.
Например, на всех страницах подключается только `AppAssetBundle`, расширения просто минифицирует его.
Но в одном из разделов во вьюхе подключается доп скрипт, например
```php
$this->registerJsFile('/js/user/edit.js');
```
В этом случае расширения создаст новый минифицированный пак `AppAssetBundle + /js/user/edit.js`

В Вашем случае возможно в renderPartial подключается какой-то виджет, который тянет свой AssetBundle, и расширение именно его пытается минифицировать. Теоретически, он должен минифицироваться только один раз, пока нет кэша в директории `minify`

**Comment by RsD0p9BK** [comment]
Только один раз. Но получается два инициализированных бутстрапа, которые не дают кликнуть по чекбоксу (один включает по клику, второй сразу выключает)

В yii2 кажется есть механизм, который предотвращает повторное добавление скрипта в шапку, но не в конец страницы

**Comment by rmrevin** [comment]
Рекомендую просто внутри афкс вызова не подключать assets. Это плохая практика. Скорее всего Вы используете pjax?

**Comment by RsD0p9BK** [comment]
Да, используется pAjax. Внутри подключаются бутстрап-карусели, которые и тянут за собой бутсрап.
Кстати после запроса JS скрипт добавляется в header, вместо body.

**Comment by rmrevin** [comment]
Значит всё верно. Вам требуется не подключать assets внутри ajax действия. Тогда pjax не будет подключать assets повторно. Вместе подключения внутри ajax, Вам нужно подключить бандл виджета заранее. А внутри ajax сделать только инициализацию скрипта виджета.

**Comment by whale001** [comment]
У меня похожая проблема, есть большой список скриптов в AppAsset, при ajax запросе, если даже включить следующие бандлы yii\web\JqueryAsset, yii\validators\ValidationAsset, yii\widgets\ActiveFormAsset в AppAsset, то при использование в ajax запросе ActiveForm, они всё равно будут добавлены, minify в этом случае добавляет просто весь (полный) набор скриптов (в одном минифицированном файле), я решил эту проблему расширением rmrevin\yii\minify\View скопировал один метод renderBodyEndHtml()  и добавил условие (первый строки метода)

`        if (!$ajaxMode && !empty($this->jsFiles[self::POS_END])) {
            $lines[] = implode("\n", $this->jsFiles[self::POS_END]);
        }`
То, что предлагает RsD0p9BK, подойдет не всем, т.к. в этом случае будут  удалены в том числе обычные скрипты, а не только дублирующие бандлы.

Ошибка работы получается в том, что при ajax запросе нужно формировать новый файл для нового небольшого набора подключенных скриптом, а не добавлять в ответ полный уже созданный файл.

**Comment by rmrevin** [comment]
@whale001 Добрый

**Comment by whale001** [comment]
Сама проблема в общем в том, что не все библиотеки "терпят" повторное подключение.

**Comment by rmrevin** [comment]
@whale001 это Вы сегодня письмо написали, ещё не успел протестировать с семантиком. Скорее всего нужно использовать уже минифицированную версию. Либо текеущий минификатор ломает скрипт (такое бывает, когда разработчики плагинов не ставят `;`, например).

**Comment by whale001** [comment]
Да, я писал, потом уже нашел эту тему. Дело именно в повторном подключении через ajax, а не в том, что скрипты не работают в минифицированном виде. В письме, я , пожалуй, не правильно описал проблему.

**Comment by whale001** [comment]
Могу собрать простой пример для воспроизведение этой особенности. Сделать?

**Comment by rmrevin** [comment]
@whale001 я думаю просто не нужно в аякс обработчике подключать бандл. Зачем это делать?

**Comment by whale001** [comment]
Он подключается автоматически, это заложено в поедении Yii2

**Comment by whale001** [comment]
Ошибка в том, что минификатор в ответ на это подключает полный файл, а не новый небольшой

**Comment by rmrevin** [comment]
@whale001 
В yii не заложено автоматическое подключение бандла. Вы подключаете его где-то самостоятельно. Как раз в ajax запросах он не должен подключаться. 

В yii заложена возможность понимать скрипты, которые приходят вместе с ответом сервера. А какие Вы там подключаете скрипты, это уже дело Ваших рук.

Минификатор минифицирует всё что попадает в `view->jsFiles` `view->cssFiles`.

**Comment by whale001** [comment]
vendor\yiisoft\yii2\widgets\ActiveForm.php:200

**Comment by rmrevin** [comment]
Это подключение бандла виджета. Он не подключает Ваш основной бандл.

**Comment by whale001** [comment]
Иными словами Вы предлагаете не использовать или переопределять поведение ActiveForm

**Comment by whale001** [comment]
Основной подключается один раз в layout

**Comment by rmrevin** [comment]
Ещё раз сформулируйте, в чём проблема? В аякс ответе где нет лейаута минификатор подключает основной бандл? Покажите тест.

**Comment by whale001** [comment]
Сейчас сделаю

**Comment by whale001** [comment]
Оказалось, это связано с другой особенностью - повторное добавление библиотеки jquery, при использовании minify и добавлении всех файлов одним - ошибка есть, без использования minify , когда из ajax запроса файлы добавляются по одному - ошибки нет. Буду разбираться.

**Comment by whale001** [comment]
Разобрался с minify не срабатывает

**Comment by whale001** [comment]
Заменить строку vendor\rmrevin\yii2-minify-view\View.php:188
на 
`if (true === $this->enableMinify && !$ajaxMode) {`

**Comment by whale001** [comment]
создал pull request https://github.com/rmrevin/yii2-minify-view/pull/31
