### ISSUE TITLE
composer install

### ISSUE THREAD

**Issue by chrisb34** [rmrevin/yii2-minify-view#23]
I'm using the advanced extended template where all sources are held in _protected and therefore the vendor folder is _protected/vendor.

Your composer definition is trying to install into just /vendor and is therefore not accessible to any of the source code.

Is this due to the Type: yii2-extension
rather than type: library that most other extensions seem to use?

**Comment by rmrevin** [comment]
Do not understand. How can type affect of installation? You some kind of modified installation process?
p.s. I'm sorry for the long answer. Missed notice.

**Comment by chrisb34** [comment]
Hi Revin

Actually, I figured out the problem.  I’ve been using the Advanced enhanced Yii template which puts the vendor directory under _protected/vendor but I did not update my composer.json, which was still pointing to /vendor.

Thanks for your reply
Chris

**Comment by rmrevin** [comment]
I am pleased that the problem was solved.
