### ISSUE TITLE
No such file in css

### ISSUE THREAD

**Issue by ZAYEC77** [rmrevin/yii2-minify-view#32]
Hello, I have a problem with CSS import.
When I have import like this:

`@import url("animate.min.css");`
it cause exception:

`file_get_contents(/css/alpha.css): failed to open stream: No such file or director`

**Comment by rmrevin** [comment]
Hey. By mistake, it happens with other imports. Show is the place where connects alpha.css

**Comment by ZAYEC77** [comment]
I think problem can be fixed by adding base path to file path.
E.g. in file `CSS.php` [line 218](https://github.com/rmrevin/yii2-minify-view/blob/master/components/CSS.php#L218)
change to
`$result = file_get_contents(\Yii::getAlias($this->view->base_path . $url));`

I try, it works for me, but I'm not sure that it will be better solution.

**Comment by rmrevin** [comment]
It looks fine. It is necessary to add a check that there is no url external resource, and local file and write a test for this case. I'll be glad to to accept pull request.

**Comment by ZAYEC77** [comment]
PR is not a problem, but I don't know how to test this case.

**Comment by rmrevin** [comment]
The extension has unit tests. We need to add a test that checks for import from an external url and local file. Nothing difficult.

**Comment by rmrevin** [comment]
Merged. Thanks.
