### ISSUE TITLE
When there is no css files to minify

### ISSUE THREAD

**Issue by pedrammehrdad** [rmrevin/yii2-minify-view#36]
Thanks for this plugin.
In components/CSS.php file line 28 function minify,
When there is no file to minify foreach returns "Invalid argument supplied for foreach()" 
Correct me if i'm wrong, I think there should be "if(!empty($cssFiles))".

**Comment by amoracr** [comment]
Hello,
Thank you for you hard work, your plugin is very usefull. 
I got this this problem whenever I try to show content in a modal. The user clicks on a row and it should open a modal with the detailed view of selected row. 
Thanks in advance.

**Comment by rmrevin** [comment]
@pedrammehrdad Thank you for reporting the problem. Fix on the way in the near future.

**Comment by rmrevin** [comment]
@amoracr Write a separate issue and describe more in detail that did not work.

**Comment by zakdma** [comment]
The same with JS.php line 23
Add if(!empty($jsFiles)) {

**Comment by rmrevin** [comment]
fixed in version `1.11.0`
