### ISSUE TITLE
Performance - compress_output

### ISSUE THREAD

**Issue by OndrejVasicek** [rmrevin/yii2-minify-view#37]
I’d like to just suggest, that in docs could be written information that turning the `compress_output` directive `on` can have significant performance impact.

40-50 ms on medium page. More html, bigger impact every visit, because there isn’t any caching.

The main point is, that if you use gzip compression on you server (which people usually does), there is no other size reduction at all (less then kB). So I’d recommend to turn this directive `off` on default and mention it in docs with the reasons.

**Comment by rmrevin** [comment]
Hello Ondrej.
That option already by default false - https://github.com/rmrevin/yii2-minify-view/blob/master/View.php#L99
It is only in the readme is for example true

**Comment by OndrejVasicek** [comment]
Oh, I didn’t notice. Thanks for the reply.
