### ISSUE TITLE
Not working with 2amigos/yii2-ckeditor-widget

### ISSUE THREAD

**Issue by pacificsoftdevld** [rmrevin/yii2-minify-view#38]
Thanks for your wonderful extension!
I have a problem with 2amigos/yii2-ckeditor-widget. It not show when using your extension.
Thanks any help. :)

**Comment by rmrevin** [comment]
Hello. Thanks for issue.
We need a demo app which will reproduce the bug, thanks.

**Comment by rmrevin** [comment]
CKeditor uses dynamically loaded scripts. To combine these two extensions, update yii2-minify-view extension to version 1.12.* and add assets of the editor to the exclude section
```php
'components' => [
    'view' => [
        'class' => \rmrevin\yii\minify\View::class,
        'excludeBundles' => [
            \dosamigos\ckeditor\CKEditorWidgetAsset::class,
            \dosamigos\ckeditor\CKEditorAsset::class,
        ],
    ],
],
```
Works fine 
http://playground.rmrevin.com/minify/test-38

**Comment by pacificsoftdevld** [comment]
Wonderful! It work great!
Thanks for your support.
