### ISSUE TITLE
Google: Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by newerton** [rmrevin/yii2-minify-view#41]
It is possible to leave the CSS in the <style> tag, instead of the file?

**Error PageSpeed Insights**
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.

Some interesting features that you could implement.
[https://github.com/skeeks-semenov/yii2-assets-auto-compress](url)

**Comment by rmrevin** [comment]
Hi. To change the order of connection styles, you need to expand your own `View` class and override the methods `renderHeadHtml` and `renderBodyEndHtml`.

The responsibilities of this extension is not included to change the boot order.
