### ISSUE TITLE
Compress Inline code

### ISSUE THREAD

**Issue by kr0lik** [rmrevin/yii2-minify-view#42]
Is it possible to add inline scripts compression and packaging them in a file?

**Comment by guzuomuse** [comment]
+1

**Comment by guzuomuse** [comment]
i think it's neccesary to compress inline js or css include @import style; like the html-compressor

**Comment by rmrevin** [comment]
@kr0lik @guzuomuse If we try to shove inline js \ css in a compressed file, it may result in a violation of the order of boot scripts \ styles, which in turn will entail the occurrence of errors. I can imagine how it is possible to compress inline data. But how to combine them with compressed files, can not imagine.

If you have any ideas, send pull reqest with the tests.

**Comment by kr0lik** [comment]
No. Usually, in yii all the scripts are inserted after script files. It is possible to make a variable in config like js_length and  js_inline_compress. And if js_inline_compress = true, we look length if inline-scripts and if it more or equal js_length, we create a file to paste the code, compress and instead of code displays a link to the file. How do I get time, I will try to send pull reqest.

**Comment by rmrevin** [comment]
@kr0lik okay, i wait.

**Comment by rmrevin** [comment]
Closed for lack of response.
