### ISSUE TITLE
Скорость....

### ISSUE THREAD

**Issue by m00nk** [rmrevin/yii2-minify-view#43]
Все работает отлично, но есть одно "но": слишком много времени уходит на "компиляцию" файлов. Потом все летает, но вот первый заход на страницу длится около 10-15 секунд даже на локальной машине (nginx + php7). А страница с TinyMCE генерировалась 46 секунд. :(

Это слишком медленно.

Я в коде не рылся, но как я понял, скрипт производит полную "компиляцию" при любом, даже малейшем изменении в списке минифицируемых файлов. Т.е. есть страница, которой нужны jQuery и Bootstrap, для нее скрипт уже собрал пакеты и на других страницах с такими же запросами будут отдаваться уже собранные пакеты, но если новая страница хочет те же jQuery и Bootstrap и еще один маленький файл стилей, то весь процесс сборки для нее начинается с начала. :-(

Как Вам такой вариант: при сборке скрипт минифицирует каждый файл (jquery.js, bootstrap.css и т.д.) _отдельно_ и складывает их в специальную папку внутри `runtime`. А затем просто склеивает их в наборы для конкретных страниц (как и сейчас). Т.е. для описанного выше случая, когда страница хочет jQuery и Bootstrap и еще один маленький файл стилей, скрипту не придется минифицировать все - достаточно прогнать минификацию только для маленького файла стилей, а затем склеить пакеты из уже минифицированных ранее файлов jQuery и Bootstrap. 

Это должно дать хороший прирост в скорости. Что думаете?

**Comment by rmrevin** [comment]
Это хорошая идея. Можно реализовать. Пришлёте pull request?

**Comment by m00nk** [comment]
Это врядли. Надеялся, что Вы реализуете.

**Comment by rmrevin** [comment]
Добрый вечер. Промежуточное кеширование частей скриптов и стилей реализовано в версии 2.0.

**Comment by m00nk** [comment]
Только сейчас заметил Ваш ответ. Спасибо.
