### ISSUE TITLE
Determining minification

### ISSUE THREAD

**Issue by jaiminmoslake7020** [rmrevin/yii2-minify-view#50]
@rmrevin  I want to know how it determines to re-minify all the files again. As it is re-minifying my asset bundles on random requests. Which has same asset bundles? What will happen when there is no change in assets. Will it going to minify them again?  Does it use timestamp with files?

**Comment by rmrevin** [comment]
Component compresses only changed files. To do this, it checks either the modification date of the file or the hash of a file (configurable with the setting View->fileCheckAlgorithm)
