### ISSUE TITLE
plz update your repo

### ISSUE THREAD

**Issue by hooman-pro** [rmrevin/yii2-minify-view#52]
Hi in php 7.1.13 I see a error in your repo dependency "mrclay/minify". error is in "CSSmin" class in this method:
 private function normalize_int($size)
    {
        if (is_string($size)) {
            switch (substr($size, -1)) {
                case 'M': case 'm': return $size * 1048576;
                case 'K': case 'k': return $size * 1024;
                case 'G': case 'g': return $size * 1073741824;
            }
        }

        return (int) $size;
    }
it is because $size has "M" suffix like  "300M" and in new php version it can not multiple, but work in older php version.

I found that mrclay/minify have new version 3 and i suggest you to update your repo for compatibility with this new version.

**Comment by CyanoFresh** [comment]
Same

**Comment by CyanoFresh** [comment]
https://github.com/rmrevin/yii2-minify-view/pull/53

**Comment by rmrevin** [comment]
Hi. I'm sorry for the long answer. I was not available.
Fixed in version `1.15.0`

**Comment by hooman-pro** [comment]
thank you . i think you forget that push update button in packagist, yet last version is 1.14.4
when i try to update it:
composer update rmrevin/yii2-minify-view
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

https://packagist.org/packages/rmrevin/yii2-minify-view
