### ISSUE TITLE
Internal server error in you new version !!!! :-(((

### ISSUE THREAD

**Issue by zxczxc12** [rmrevin/yii2-minify-view#54]
I'm just updated to your new version and my site is dead :-(

Class 'CSSmin' not found

I returned to version 1.14.4 and all ok

**Comment by rmrevin** [comment]
Update dependencies. Package `mrclay/minify` should be upgraded to version 3.0

**Comment by zxczxc12** [comment]
in my composer.json
...
"rmrevin/yii2-minify-view": "^1.15"
...

> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 8 installs, 2 updates, 0 removals
  - Installing tubalmartin/cssmin (v3.3.1): Loading from cache
  - Installing pimple/pimple (dev-master 93ec38f): Cloning 93ec38f1df from cache
  - Installing psr/container (dev-master b7ce3b1): Cloning b7ce3b1764 from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing mrclay/props-dic (2.2.0): Loading from cache
  - Installing monolog/monolog (1.x-dev 35c07a8): Cloning 35c07a81de from cache
  - Installing intervention/httpauth (2.0.2): Loading from cache
  - Installing mrclay/jsmin-php (2.3.2): Loading from cache
  - Updating mrclay/minify (2.x-dev a36e201 => dev-master 79e5a22):  Checking out 79e5a22321
  - Updating rmrevin/yii2-minify-view (1.14.4 => 1.15.0): Loading from cache
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Package rubaxa/fileapi is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file

-------

So,  mrclay/minify updated

**Comment by rmrevin** [comment]
But you are using an unstable version of the package. In production projects, you should use only stable versions. Add the line `"minimum-stability": "stable"` to `composer.json`

**Comment by zxczxc12** [comment]
Thank you !!!

**Comment by rmrevin** [comment]
I'm glad I could help. Good luck.
