### ISSUE TITLE
minify html 

### ISSUE THREAD

**Issue by hooman-pro** [rmrevin/yii2-minify-view#55]
hi html minify have a problem . when i try it with this html:

> <?php
use hoomanMirghasemi\jdf\Jdf;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use common\models\BaseUser;
use common\models\Country;
use common\models\State;
use common\models\CashReport;
use common\models\LoginForm;
use common\models\SearchInfo;
use common\widgets\Alert;
use yii\web\View;
use frontend\assets\AppAsset;
use yii\bootstrap\ActiveForm;

$this->registerJsFile("/js/jquery.autosize.js");
$this->registerJsFile(PROTOCOL.DOMAIN."/bootstrap/js/bootstrap.rtl.js", ['position'=>View::POS_END]);
if (Yii::$app->params['analytics']) {
    $this->registerJsFile("/js/google-analytics.js", ['position'=>View::POS_END]);
}

$this->registerJsFile("/js/menu_xs/modernizr.custom.25376.js", ['position'=>View::POS_END]);
$this->registerJsFile("/js/menu_xs/classie.js", ['position'=>View::POS_END]);
$this->registerJsFile("/js/menu_xs/menu.js",['position'=>View::POS_END]);
$this->registerJsFile("/js/main.js",['position'=>View::POS_END]);

$this->registerCssFile(PROTOCOL.DOMAIN."/fonts/fontawesome/font-awesome.css");
$this->registerCssFile("/css/main-ask.css");
$this->registerCssFile("/css/login-page.css");
$this->registerCssFile("/css/other-page-header.css");
$this->registerCssFile("/css/footer.css");
$this->registerCssFile("/bootstrap/css/bootstrap.rtl.min.css");

$this->registerCssFile( "/css/cropiframe.css");
$this->registerCssFile("/css/iframe.css");
$this->registerCssFile("/css/menu_xs/normalize.css");
$this->registerCssFile( "/css/menu_xs/demo.css");
$this->registerCssFile("/css/menu_xs/component.css");
$this->registerCssFile("/css/layouts/body-footer2.css");
$this->registerCssFile("/css/layouts/body-footer1.css");
$this->registerCssFile("/css/layouts/main.css");

AppAsset::register($this);

?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <meta name="language" content="fa" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta name="HandheldFriendly" content="true"/>
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <meta name="google-site-verification" content="oKj208q33gcuWhG0Oaaf5Ok3_2pNChW9QGwOkkPMSa4" />
        <style>
            @font-face {
                font-family: 'Btitr';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.eot'); /* IE9 Compatibility Modes */
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.eot?') format('eot'), /* IE6-IE8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.woff') format('woff'), /* Modern Browsers */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.ttf') format('truetype');
            }
            @font-face {
                font-family: 'IRANSans';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.eot'); /* IE9 Compatibility Modes */
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.eot?') format('eot'), /* IE6-IE8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.woff') format('woff'), /* Modern Browsers */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.ttf') format('truetype');
            }
            @font-face {
                font-family: 'IRANSansnum';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).eot');
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).eot?#iefix') format('eot'),  /* IE6–8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).woff2') format('woff2'),  /* Chrome36+, Opera24+*/
                url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).woff') format('woff'),  /* FF3.6+, IE9, Chrome6+, Saf5.1+*/
                url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).ttf') format('ttf');
                font-weight: normal;
            }
            @font-face {
                font-family: 'Bkoodak';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.eot'); /* IE9 Compatibility Modes */
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.eot?') format('eot'), /* IE6-IE8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.woff') format('woff'), /* Modern Browsers */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.ttf') format('truetype');
            }
        </style>
        <?php if (Yii::$app->params['searchEngineIndex']): ?>
            <meta content="INDEX,FOLLOW" name="robots">
        <?php else: ?>
            <meta content="NOINDEX, NOFOLLOW" name="robots">
        <?php endif; ?>
        <?php if (Yii::$app->params['alexa']): ?>
            <script type="text/javascript">
                _atrk_opts = {atrk_acct: "6DHQm1a4KM+25T", domain: "salamatyar.com", dynamic: true};
                (function () {
                    var as = document.createElement('script');
                    as.type = 'text/javascript';
                    as.async = true;
                    as.src = "https://d31qbv1cthcecs.cloudfront.net/atrk.js";
                    var s = document.getElementsByTagName('script')[0];
                    s.parentNode.insertBefore(as, s);
                })();
            </script>
            <noscript><img src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=6DHQm1a4KM+25T" style="display:none" height="1" width="1" alt="" /></noscript>
        <?php endif; ?>
        <?php $this->head() ?>
    </head>
    <body>

    <div id="perspective" class="perspective effect-moveleft">

        <nav class="outer-nav right vertical">
            <ul class="nav navbar-nav bg_navbar visible-xs">
                <li class="margin-li-menu media-menu-margin margin_right">
                    <a href="<?= PROTOCOL.DOMAIN  ?>" class="third after add" title="سلامتیار">
                        <i class="fa fa-home fa-home_menu_xs"></i><span class="text">خانه</span>
                    </a>
                </li>
                

            </ul>
        </nav>
    </div>
    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>

> 

this work 

and with this html:

> 
<?php
use hoomanMirghasemi\jdf\Jdf;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use common\models\BaseUser;
use common\models\Country;
use common\models\State;
use common\models\CashReport;
use common\models\LoginForm;
use common\models\SearchInfo;
use common\widgets\Alert;
use yii\web\View;
use frontend\assets\AppAsset;
use yii\bootstrap\ActiveForm;

$this->registerJsFile("/js/jquery.autosize.js");
$this->registerJsFile(PROTOCOL.DOMAIN."/bootstrap/js/bootstrap.rtl.js", ['position'=>View::POS_END]);
if (Yii::$app->params['analytics']) {
    $this->registerJsFile("/js/google-analytics.js", ['position'=>View::POS_END]);
}

$this->registerJsFile("/js/menu_xs/modernizr.custom.25376.js", ['position'=>View::POS_END]);
$this->registerJsFile("/js/menu_xs/classie.js", ['position'=>View::POS_END]);
$this->registerJsFile("/js/menu_xs/menu.js",['position'=>View::POS_END]);
$this->registerJsFile("/js/main.js",['position'=>View::POS_END]);

$this->registerCssFile(PROTOCOL.DOMAIN."/fonts/fontawesome/font-awesome.css");
$this->registerCssFile("/css/main-ask.css");
$this->registerCssFile("/css/login-page.css");
$this->registerCssFile("/css/other-page-header.css");
$this->registerCssFile("/css/footer.css");
$this->registerCssFile("/bootstrap/css/bootstrap.rtl.min.css");

$this->registerCssFile( "/css/cropiframe.css");
$this->registerCssFile("/css/iframe.css");
$this->registerCssFile("/css/menu_xs/normalize.css");
$this->registerCssFile( "/css/menu_xs/demo.css");
$this->registerCssFile("/css/menu_xs/component.css");
$this->registerCssFile("/css/layouts/body-footer2.css");
$this->registerCssFile("/css/layouts/body-footer1.css");
$this->registerCssFile("/css/layouts/main.css");

AppAsset::register($this);

?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <meta name="language" content="fa" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta name="HandheldFriendly" content="true"/>
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <meta name="google-site-verification" content="oKj208q33gcuWhG0Oaaf5Ok3_2pNChW9QGwOkkPMSa4" />
        <style>
            @font-face {
                font-family: 'Btitr';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.eot'); /* IE9 Compatibility Modes */
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.eot?') format('eot'), /* IE6-IE8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.woff') format('woff'), /* Modern Browsers */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BTitrBold.ttf') format('truetype');
            }
            @font-face {
                font-family: 'IRANSans';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.eot'); /* IE9 Compatibility Modes */
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.eot?') format('eot'), /* IE6-IE8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.woff') format('woff'), /* Modern Browsers */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/IRANSans.ttf') format('truetype');
            }
            @font-face {
                font-family: 'IRANSansnum';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).eot');
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).eot?#iefix') format('eot'),  /* IE6–8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).woff2') format('woff2'),  /* Chrome36+, Opera24+*/
                url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).woff') format('woff'),  /* FF3.6+, IE9, Chrome6+, Saf5.1+*/
                url('<?= PROTOCOL.DOMAIN ?>/fonts/num/IRANSansWeb(FaNum).ttf') format('ttf');
                font-weight: normal;
            }
            @font-face {
                font-family: 'Bkoodak';
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.eot'); /* IE9 Compatibility Modes */
                src: url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.eot?') format('eot'), /* IE6-IE8 */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.woff') format('woff'), /* Modern Browsers */
                url('<?= PROTOCOL.DOMAIN ?>/fonts/BKoodakBold.ttf') format('truetype');
            }
        </style>
        <?php if (Yii::$app->params['searchEngineIndex']): ?>
            <meta content="INDEX,FOLLOW" name="robots">
        <?php else: ?>
            <meta content="NOINDEX, NOFOLLOW" name="robots">
        <?php endif; ?>
        <?php if (Yii::$app->params['alexa']): ?>
            <script type="text/javascript">
                _atrk_opts = {atrk_acct: "6DHQm1a4KM+25T", domain: "salamatyar.com", dynamic: true};
                (function () {
                    var as = document.createElement('script');
                    as.type = 'text/javascript';
                    as.async = true;
                    as.src = "https://d31qbv1cthcecs.cloudfront.net/atrk.js";
                    var s = document.getElementsByTagName('script')[0];
                    s.parentNode.insertBefore(as, s);
                })();
            </script>
            <noscript><img src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=6DHQm1a4KM+25T" style="display:none" height="1" width="1" alt="" /></noscript>
        <?php endif; ?>
        <?php $this->head() ?>
    </head>
    <body>

    <div id="perspective" class="perspective effect-moveleft">

        <nav class="outer-nav right vertical">
            <ul class="nav navbar-nav bg_navbar visible-xs">
                <li class="margin-li-menu media-menu-margin margin_right">
                    <a href="<?= PROTOCOL.DOMAIN  ?>" class="third after add" title="سلامتیار">
                        <i class="fa fa-home fa-home_menu_xs"></i><span class="text">خانه</span>
                    </a>
                </li>
                <li class="margin-li-menu">
                    <a href="<?=  PROTOCOL.DOMAIN .'/doctors'  ?>" class="third after add" title="پزشکان سلامتیار">
                        <i class="fa fa-user-md fa-user-md_menu_xs"></i><span class="text">پزشکان سلامتیار</span>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>

> 
it is not working!!

see diffrent of that tow code only addtional li

**Comment by hooman-pro** [comment]
so i try to find out what is the problem but not clear thing was that! for example once more than 15 character in img title was reason of not  working html comperosor!!

**Comment by rmrevin** [comment]
Format the code normally and specify the location of the change. Such code can not be read. Try to replace the Arabic words with English ones and check the minification, maybe a problem with the encoding.

**Comment by rmrevin** [comment]
Try to use version 2.0. There is an updated engine minification of html. Maybe this will solve Your problem.
