### ISSUE TITLE
compressed on each pageload?

### ISSUE THREAD

**Issue by gvanto** [rmrevin/yii2-minify-view#57]
Thanks for a great component!

Just have a question re: its operation - are the files compressed on each pageload? (worried about page load time if this is the case...) 

I'm comparing this component vs using something like grunt to create .min.js files then adding these to source control and pointing to on PROD env (this way min files generated once only).

thanks
gvanto

**Comment by rmrevin** [comment]
No. Component once compresses your assets for each page then takes the data from the cache. If scripts or styles change, the component re-compresses them and puts it in the cache.

**Comment by gvanto** [comment]
Awesome thanks Revin, that is good functionality!
