### ISSUE TITLE
Missed .gitignore in folder

### ISSUE THREAD

**Issue by springimport** [rmrevin/yii2-minify-view#58]
Git status after adding extension.
```
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   composer.json
        modified:   composer.lock
        modified:   frontend/config/main.php
        new file:   frontend/web/minify/2068bd333df95e0693e6d53c513f4bde2fd06390.js
        new file:   frontend/web/minify/3bbef2fa2d1790f3eecdfcd429535a39990f5e76.css
        new file:   frontend/web/minify/a4f923bee4b1b84096b334981a6f4a3523916862.js
        new file:   frontend/web/minify/a67604cb503b0c1b5a21eb71bcec724b091cf55c.js
```

I think extension should add this file automatically after creating `minify` folder  `/frontend/web/minify/.gitignore`.

**Comment by rmrevin** [comment]
@springimport You have to add this directory to ignore. Since not all projects use git (there are other vcs). And there are times when builded and minfied frontend app falls into vcs.

**Comment by springimport** [comment]
@rmrevin But yii2 adds this file after installation. And I see your extension name contain "yii2".
