### ISSUE TITLE
Empty file and bad links

### ISSUE THREAD

**Issue by lukicdarkoo** [rmrevin/yii2-minify-view#6]
In my `@app/web` folder there is new folder called `minify` and there is **empty** .css file (only `@charset "UTF-8";`).

Also, script generates bad links
`<link href="/minify/da39a3ee5e6b4b0d3255bfef95601890afd80709.css" rel="stylesheet">`
but it should be something like this
`<link href="my_app_name/minify/da39a3ee5e6b4b0d3255bfef95601890afd80709.css" rel="stylesheet">`

I use default configuration.

**Comment by rmrevin** [comment]
Sorry for the long answer. Task lost.
You can configure the link using the parameter [minify_path in class View](https://github.com/rmrevin/yii2-minify-view/blob/master/View.php#L25).
About empty file. Check the current version 1.7.6 the problem persists?

**Comment by o-shabashov** [comment]
Привет.
Даже в последней (dev-master) версии всё ещё есть этот баг с пустым CSS и JS.

Подскажи, пожалуйста, как нужно выставить параметры, чтобы заработало при такой структуре:

project/sources/web/web/index.php

Проект открывается из поддиректории типа http://localhost/project/sources/web/web

С дефолтными настройками (@app/web) в @webroot/minify лежат два пустых файла css и js и подключаются на странице как http://localhost/minify/da39a3ee5e6b4b0d3255bfef95601890afd80709.js

**Comment by rmrevin** [comment]
Fixed in version 1.8.0
