### ISSUE TITLE
Pjax does not work with the current configuration.

### ISSUE THREAD

**Issue by temirovgroup** [rmrevin/yii2-minify-view#70]
Hello!

Pjax does not work with the current configuration. It is used for adding comments to the site, so the first time it is added without reloading, and the second time it reloads the page. This happens if the 'concatJs' parameter is true.

Please help solve this problem. I've already broken my head.. there are no errors in the console, but the page is reloaded if you try to use the form a second time (in one session). There is no redirect on the server side, the comment is added successfully but with a reboot. 

I apologize for my English.

`<?php
        'view' => [
	        'class' => '\rmrevin\yii\minify\View',
	        'enableMinify' => !YII_DEBUG,
//	        'enableMinify' => YII_DEBUG,
	        'concatCss' => true, // concatenate css
	        'minifyCss' => true, // minificate css
	        'concatJs' => true, // concatenate js - if 'false' - Pjax worked.
	        'minifyJs' => true, // minificate js
	        'minifyOutput' => true, // minificate result html page
	        'webPath' => '@web', // path alias to web base
	        'basePath' => '@webroot', // path alias to web base
	        'minifyPath' => '@webroot/source', // path alias to save minify result
	        'jsPosition' => [
		        \yii\web\View::POS_END,
	        ], // positions of js files to be minified
	        'forceCharset' => 'UTF-8', // charset forcibly assign, otherwise will use all of the files found charset
	        'expandImports' => true, // whether to change @import on content
	        'compressOptions' => ['extra' => true], // options for compress
	        'excludeFiles' => [
//		        'jquery.js', // exclude this file from minification
//		        'app-[^.].js', // you may use regexp
	        ],
	        'excludeBundles' => [
	        	\mihaildev\ckeditor\Assets::class,

//		        \app\helloworld\AssetBundle::class, // exclude this bundle from minification
	        ],
        ],
?>
`

**Comment by rmrevin** [comment]
@temirovgroup Most likely the problem is on the side of your scripts. After reloading the form, dom model of page changes and all js event handler bindings are lost. Verify handlers persist across page reloads.

**Comment by temirovgroup** [comment]
> 
> 
> @temirovgroup Most likely the problem is on the side of your scripts. After reloading the form, dom model of page changes and all js event handler bindings are lost. Verify handlers persist across page reloads.

The bottom line is that if you disable concatJS, everything works. And I didn't write the handlers myself, everything works on the standard Yii2 form + Pjax.

**Comment by rmrevin** [comment]
If you load the script inside an ajax request, then it won't work in script concatenation. Without a demo stand, I can do nothing more to help.

**Comment by temirovgroup** [comment]
> 
> 
> If you load the script inside an ajax request, then it won't work in script concatenation. Without a demo stand, I can do nothing more to help.

I'm sorry, this is project

http://partner.eda.menu/admin
phone: 8888888888
pass: admin

next step: http://partner.eda.menu/stock/testovaa-akcia

https://prnt.sc/uatpo3

Help me :(

**Comment by temirovgroup** [comment]
this code:

`
	/**
	 * @param $url
	 *
	 * @return string
	 * @throws HttpException
	 */
	public function actionView($url)
	{
		if (empty($data = Post::findOne(['url' => $url]))) {
			throw new HttpException(404);
		}
		
		$this->setMeta(
			$data->title,
			$data->meta_description,
			$data->meta_keyword
		);
		
		$session = Yii::$app->getSession();
		
		// Модель комментария
		$model = new Comment();
		
		// Модель подтверждения через СМС
		$modelConfirmation = new Confirmation();
		
		if (Yii::$app->getRequest()->isPjax && $model->load(Yii::$app->getRequest()->post()) && $model->validate()) {
			// Если гость, то сохраняем номер телефона в сессию и модель в кэш, направляем на подтверждение в СМС.
			if (Yii::$app->getUser()->isGuest) {
				// Layout change
				$this->layout = false;
				
				$session->set('phone', $model->phone);
				$session->set('modelComment', $model);
				
				if (empty($user = User::findOne(['phone' => $model->phone]))) {
					(new User())->createUser($model);
				} else {
					(new Collector())->sendConfrimSms($user);
				}
				
				Yii::$app->getSession()->setFlash('info', 'Введите код из СМС');
				
				return $this->renderAjax('_confirmation-view', [
					'data' => $data,
					'modelConfirmation' => $modelConfirmation,
				]);
			} else {
				if ($model->save()) {
					Yii::$app->getSession()->setFlash('success', 'Комментарий успешно добавлен!');
				}
			}
		}
		
		if (Yii::$app->getRequest()->isPjax && $modelConfirmation->load(Yii::$app->getRequest()->post())) {
			// Если код неверный
			if (!$modelConfirmation->confirm()) {
				// Layout change
				//$this->layout = false;
				
				Yii::$app->getSession()->setFlash('warning', 'Неверный код из СМС!');
				
				$modelConfirmation->sms_code = '';
				
				return $this->render('_confirmation-view', [
					'data' => $data,
					'modelConfirmation' => $modelConfirmation,
				]);
			} else {
				// Модель из сессии
				$modelComment = $session->remove('modelComment');
				
				// Модель комментария
				$model = new Comment();
				$model->name = $modelComment->name;
				$model->phone = $modelComment->phone;
				$model->text = $modelComment->text;
				$model->target_id = $modelComment->target_id;
				$model->pid = $modelComment->pid;
				$model->type = $modelComment->type;
				
				if ($model->save()) {
					Yii::$app->getSession()->setFlash('success', 'Комментарий успешно добавлен!');
				}
			}
		}
		
		// Комментарии к записи
		$comment = Comment::find()->where([
			'pid' => $data->id,
			'type' => (new Collector())->getClassName($data),
			'target_id' => 0,
		])->orderBy(['created_at' => SORT_DESC])
		  ->with(['user', 'targetComment'])
		  ->all();
		
		// Акции
		$stock = Stock::find()->where(['is_active' => '1'])
		              ->andWhere(['>=', 'lifetime', time()])
		              ->all();
		
		// Новости и статьи
		$post = Post::find()->where(['is_active' => '1'])
		                    ->andWhere(['!=', 'id', $data->id])
				            ->orderBy(['created_at' => SORT_DESC])
				            ->limit(10)
				            ->all();
		
		// Сброс блока комментария
		$model->text = '';
		$model->target_id = '';
		
		return $this->render('view', [
			'data' => $data,
			'stock' => $stock,
			'post' => $post,
			'model' => $model,
			'comment' => $comment,
		]);
	}`



VIEW

`<?php

/**
 * Created by PhpStorm.
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this \yii\web\View */
/* @var $data \app\modules\admin\models\Stock|null */
/* @var $model \app\modules\admin\models\Comment */
/* @var $comment array|\yii\db\ActiveRecord[] */
/* @var $stock \app\modules\admin\models\Stock|[] */
/* @var $post \app\modules\admin\models\Post|[] */

$collector = new \app\models\Collector();
?>

<div class="page-body-wrap">
	<div class="c_g">
		<svg enable-background="new 0 0 512 512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><g><g><path d="m256 512c-68.38 0-132.667-26.629-181.02-74.98-48.351-48.353-74.98-112.64-74.98-181.02s26.629-132.667 74.98-181.02c48.353-48.351 112.64-74.98 181.02-74.98s132.667 26.629 181.02 74.98c48.351 48.353 74.98 112.64 74.98 181.02s-26.629 132.667-74.98 181.02c-48.353 48.351-112.64 74.98-181.02 74.98zm0-482c-60.367 0-117.12 23.508-159.806 66.194s-66.194 99.439-66.194 159.806 23.508 117.12 66.194 159.806 99.439 66.194 159.806 66.194 117.12-23.508 159.806-66.194 66.194-99.439 66.194-159.806-23.508-117.12-66.194-159.806-99.439-66.194-159.806-66.194z"/></g><g><path d="m241 60.036h30v40.032h-30z"/></g><g><path d="m360.398 116.586h40.032v30h-40.032z" transform="matrix(.707 -.707 .707 .707 18.375 307.534)"/></g><g><path d="m411.932 241h40.032v30h-40.032z"/></g><g><path d="m365.414 360.398h30v40.032h-30z" transform="matrix(.707 -.707 .707 .707 -157.573 380.414)"/></g><g><path d="m241 411.932h30v40.032h-30z"/></g><g><path d="m111.57 365.414h40.032v30h-40.032z" transform="matrix(.707 -.707 .707 .707 -230.453 204.466)"/></g><g><path d="m60.036 241h40.032v30h-40.032z"/></g><g><path d="m116.586 111.57h30v40.032h-30z" transform="matrix(.707 -.707 .707 .707 -54.505 131.586)"/></g><g><path d="m361.892 271h-120.892v-120.892h30v90.892h90.892z"/></g></g></svg>
		<?= $collector->showDate($data->created_at) ?>
	</div>
	<div class="post-title">
		<?= $data->title ?>
	</div>
	<div class="post-thumb">
		<?php if (isset($data->vcode) && !empty(trim($data->vcode))) : ?>
			<div class="post-video-wrap">
				<iframe id="video" width="100%" src="https://www.youtube.com/embed/<?= $data->vcode ?>?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
			</div>
		<?php else : ?>
			<?= Html::img($collector->imageUrl($data, 920, null), ['alt' => $data->title]) ?>
		<?php endif; ?>
	</div>
	<div class="post-content">
		<?= $data->content ?>
	</div>
</div>

<div class="post-comment-title">
	<h3>Комментарии</h3>
</div>

<div class="page-body-wrap">
	<?php Pjax::begin(['id' => 'comment-form']) ?>
	
	<?= \lo\modules\noty\Wrapper::widget([
		'layerClass' => 'lo\modules\noty\layers\Toastr',
		'layerOptions'=>[
			// for every layer (by default)
			'layerId' => 'noty-layer',
			'customTitleDelimiter' => '|',
			'overrideSystemConfirm' => true,
			'showTitle' => false,
		],
		// default options
		'options' => [
			'closeButton' => false,
			'debug' => false,
			'newestOnTop' => true,
			
			// and more for this library...
		],
	]) ?>
	
	<?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]) ?>
	
	<?php if (Yii::$app->getUser()->isGuest) : ?>
		<div class="row comment-input">
			<div class="col-sm-6">
				<?= $form->field($model, 'name')
				         ->textInput(['placeholder' => 'Ваше имя'])
				         ->error(false)
				?>
			</div>
			<div class="col-sm-6">
				<?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::class, [
					'mask' => '+7 (999) 999-99-99',
					'options' => [
						'placeholder' => '+7 (999) 999-99-99',
					],
					'clientOptions' => [
						'clearIncomplete' => true,
					],
				])->error(false) ?>
			</div>
		</div>
	<?php endif; ?>
	
	<?= $form->field($model, 'target_id')
	         ->hiddenInput(['value' => 0])
	         ->label(false)
	         ->error(false)
	?>
	
	<?= $form->field($model, 'type')
	         ->hiddenInput(['value' => $collector->getClassName($data)])
	         ->label(false)
	         ->error(false)
	?>
	
	<?= $form->field($model, 'pid')
	         ->hiddenInput(['value' => $data->id])
	         ->label(false)
	         ->error(false)
	?>
	
	<div class="comment-textarea">
		<div class="comment-icon glyphicon glyphicon-comment"></div>
		<?= $form->field($model, 'text')
		         ->textarea(['placeholder' => 'Текст комментария...', 'rows' => 3])
		         ->label(false)
		         ->error(false)
		?>
	</div>
	
	<?= Html::submitButton('Добавить', ['class' => 'sys-btn pull-right']) ?>
	
	<div class="clearfix"></div>
	
	<?php ActiveForm::end() ?>
	<?php Pjax::end() ?>
</div>

<?php $defaultUrl = $collector->imageUrl(null, 75, 75, 58) ?>

<?php Pjax::begin(['id' => 'comment-list']) ?>

<?php foreach ($comment as $item) : ?>
	<div class="page-body-wrap">
		<div class="post-comment-wrap">
			<div class="pc-author-thumb">
				<?= Html::img($defaultUrl, ['alt' => $item->user->name, 'class' => 'lozad', 'data-src' => $collector->imageUrl($item->user, 75, 75)]) ?>
			</div>
			<div class="pc-content">
				<span><?= $item->user->name ?> - <i><?= $collector->showDate($item->created_at) ?></i></span>
				<div>
					<?= $item->text ?>
				</div>
			</div>
			<div data-id="<?= $item->id ?>" class="comment-icon comment-icon-author" title="Ответить на комментарий от <?= $item->user->name ?>">
			    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 25.625 25.625" style="enable-background:new 0 0 25.625 25.625;" xml:space="preserve"><g><path d="M12.812,0.435C5.736,0.435,0,5.499,0,11.747c0,3.168,1.479,6.028,3.855,8.082c-0.521,3.01-3.883,4.23-3.652,5.059c2.84,1.175,8.529-1.412,9.918-2.083c0.869,0.164,1.768,0.255,2.691,0.255c7.076,0,12.813-5.064,12.813-11.313S19.888,0.435,12.812,0.435z M11.904,12.218c0,3.076-1.361,4.802-4.043,5.129c-0.006,0.001-0.01,0.001-0.016,0.001c-0.029,0-0.061-0.011-0.082-0.031c-0.027-0.023-0.043-0.058-0.043-0.094V15.66c0-0.046,0.025-0.088,0.064-0.109c1.223-0.667,1.834-1.717,1.865-3.207H7.845c-0.068,0-0.125-0.056-0.125-0.125V8.286c0-0.069,0.057-0.125,0.125-0.125h3.934c0.068,0,0.125,0.056,0.125,0.125V12.218z M18.869,12.218c0,3.029-1.205,4.563-4.033,5.128c-0.008,0.001-0.016,0.002-0.024,0.002c-0.029,0-0.057-0.01-0.08-0.028c-0.029-0.023-0.045-0.06-0.045-0.097V15.66c0-0.046,0.025-0.088,0.064-0.109c1.223-0.667,1.834-1.717,1.865-3.207h-1.804c-0.068,0-0.125-0.056-0.125-0.125V8.286c0-0.069,0.057-0.125,0.125-0.125h3.932c0.07,0,0.125,0.056,0.125,0.125V12.218z"/></g></svg>
			</div>
		</div>
		<?= $collector->treeOut($item->targetComment) ?>
	</div>
<?php endforeach; ?>
<?php Pjax::end() ?>

<div class="post-slider-wrap">
	
	<div>
		<div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Похожие акции и статьи</div>
	</div>
	
	<?php $defaultUrl = $collector->imageUrl(null, 75, 75, 58) ?>
	
	<div class="owl-carousel owl-theme" id="post-slider">
		
		<?php $defaultImgUrl = $collector->imageUrl(null, 370, 235) ?>
		
		<?php foreach ($stock as $data) : ?>
			<div class="item px-2">
				<div class="fh5co_hover_news_img">
					<div class="fh5co_news_img">
						<a href="<?= $link = Url::to(['stock/view', 'url' => $data->url]) ?>">
							<?= Html::img($defaultImgUrl, ['alt' => $data->title, 'class' => 'lozad', 'data-src' => $collector->imageUrl($data, 374, 200)]) ?>
						</a>
					</div>
					<div>
						<a href="<?= $link ?>" class="d-block fh5co_small_post_heading">
							<span class=""><?= $data->title ?></span>
						</a>
						<div class="c_g">
							<svg enable-background="new 0 0 512 512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><g><g><path d="m256 512c-68.38 0-132.667-26.629-181.02-74.98-48.351-48.353-74.98-112.64-74.98-181.02s26.629-132.667 74.98-181.02c48.353-48.351 112.64-74.98 181.02-74.98s132.667 26.629 181.02 74.98c48.351 48.353 74.98 112.64 74.98 181.02s-26.629 132.667-74.98 181.02c-48.353 48.351-112.64 74.98-181.02 74.98zm0-482c-60.367 0-117.12 23.508-159.806 66.194s-66.194 99.439-66.194 159.806 23.508 117.12 66.194 159.806 99.439 66.194 159.806 66.194 117.12-23.508 159.806-66.194 66.194-99.439 66.194-159.806-23.508-117.12-66.194-159.806-99.439-66.194-159.806-66.194z"/></g><g><path d="m241 60.036h30v40.032h-30z"/></g><g><path d="m360.398 116.586h40.032v30h-40.032z" transform="matrix(.707 -.707 .707 .707 18.375 307.534)"/></g><g><path d="m411.932 241h40.032v30h-40.032z"/></g><g><path d="m365.414 360.398h30v40.032h-30z" transform="matrix(.707 -.707 .707 .707 -157.573 380.414)"/></g><g><path d="m241 411.932h30v40.032h-30z"/></g><g><path d="m111.57 365.414h40.032v30h-40.032z" transform="matrix(.707 -.707 .707 .707 -230.453 204.466)"/></g><g><path d="m60.036 241h40.032v30h-40.032z"/></g><g><path d="m116.586 111.57h30v40.032h-30z" transform="matrix(.707 -.707 .707 .707 -54.505 131.586)"/></g><g><path d="m361.892 271h-120.892v-120.892h30v90.892h90.892z"/></g></g></svg>
							<?= $collector->showDate($data->created_at) ?>
							&nbsp;|&nbsp;
							<span>Промокод: <span class="text text-warning"><?= $data->code ?></span></span>
						</div>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
		
		<?php foreach ($post as $data) : ?>
			<div class="item px-2">
				<div class="fh5co_hover_news_img">
					<div class="fh5co_news_img">
						<a href="<?= $link = Url::to(['post/view', 'url' => $data->url]) ?>">
							<?= Html::img($defaultImgUrl, ['alt' => $data->title, 'class' => 'lozad', 'data-src' => $collector->imageUrl($data, 374, 200)]) ?>
						</a>
					</div>
					<div>
						<a href="<?= $link ?>" class="d-block fh5co_small_post_heading">
							<?php if (!empty(trim($data->vcode))) : ?>
								<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve"><path style="fill:#FF5A5A;" d="M491.719,135.652c-5.658-21.512-22.33-38.455-43.498-44.205C409.853,80.999,295.348,80.999,256,80.999s-153.853,0-192.221,10.448c-21.168,5.75-37.84,22.693-43.498,44.205C10,174.644,10,255.999,10,255.999s0,81.354,10.281,120.347c5.658,21.512,22.33,38.455,43.498,44.205C102.147,430.999,198,430.999,256,430.999s153.853,0,192.221-10.448c21.168-5.75,37.84-22.693,43.498-44.205C502,337.353,502,255.999,502,255.999S502,174.644,491.719,135.652z"/><path d="M258.503,91.003c-0.009,0-0.018,0-0.027,0l-0.725-0.002c-5.515-0.015-9.975-4.491-9.973-10.003c0-0.008,0-0.016,0-0.024c0.015-5.514,4.49-9.973,10-9.973c0.01,0,0.018,0,0.028,0l0.724,0.002c5.515,0.015,9.975,4.491,9.973,10.003c0,0.008,0,0.016,0,0.024C268.488,86.544,264.013,91.003,258.503,91.003z"/><path d="M256,440.999c-6.336,0-155.641-0.123-194.849-10.8c-24.607-6.684-43.976-26.345-50.542-51.31C0.121,339.107,0,259.374,0,255.999s0.121-83.108,10.611-122.896c6.564-24.959,25.933-44.621,50.546-51.306c25.901-7.053,98.771-9.571,155.34-10.44c5.508-0.048,10.068,4.323,10.153,9.845c0.084,5.522-4.323,10.068-9.845,10.152c-78.34,1.205-131.752,4.664-150.399,9.742c-17.736,4.818-31.703,19.033-36.455,37.1C20.12,175.484,20,255.198,20,255.999c0,0.8,0.12,80.514,9.95,117.797c4.753,18.073,18.72,32.288,36.45,37.104c36.654,9.981,188.075,10.099,189.6,10.099s152.946-0.117,189.594-10.097c17.736-4.818,31.703-19.033,36.455-37.1C491.88,336.513,492,256.799,492,255.998c0-0.8-0.12-80.514-9.95-117.797c-4.753-18.073-18.72-32.288-36.45-37.104c-18.247-4.969-70.125-8.404-146.085-9.674c-5.522-0.092-9.924-4.644-9.832-10.166s4.676-9.907,10.166-9.832c54.88,0.917,125.625,3.462,151,10.373c24.607,6.684,43.976,26.345,50.542,51.31C511.879,172.891,512,252.624,512,255.999s-0.121,83.108-10.611,122.896c-6.564,24.959-25.933,44.621-50.546,51.306C411.641,440.876,262.336,440.999,256,440.999z"/><polygon style="fill:#FFFFFF;" points="208.084,185.521 332.084,257.521 208.084,329.521 "/><path d="M58,331.021c-5.523,0-10-4.477-10-10v-81.5c0-5.523,4.477-10,10-10s10,4.477,10,10v81.5C68,326.544,63.523,331.021,58,331.021z"/><path d="M58,204.139c-5.523,0-10-4.477-10-10v-0.118c0-5.523,4.477-10,10-10s10,4.477,10,10v0.118C68,199.662,63.523,204.139,58,204.139z"/><path d="M208.084,339.521c-1.723,0-3.445-0.444-4.989-1.333c-3.1-1.785-5.011-5.089-5.011-8.667v-144c0-3.577,1.911-6.882,5.011-8.667c3.1-1.785,6.917-1.778,10.011,0.019l124,72c3.082,1.79,4.979,5.084,4.979,8.648s-1.896,6.858-4.979,8.648l-124,72C211.554,339.071,209.819,339.521,208.084,339.521z M218.084,202.891v109.26l94.085-54.63L218.084,202.891z"/></svg>
							<?php endif; ?>
							<span><?= $data->title ?></span>
						</a>
						<div class="c_g">
							<svg enable-background="new 0 0 512 512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><g><g><path d="m256 512c-68.38 0-132.667-26.629-181.02-74.98-48.351-48.353-74.98-112.64-74.98-181.02s26.629-132.667 74.98-181.02c48.353-48.351 112.64-74.98 181.02-74.98s132.667 26.629 181.02 74.98c48.351 48.353 74.98 112.64 74.98 181.02s-26.629 132.667-74.98 181.02c-48.353 48.351-112.64 74.98-181.02 74.98zm0-482c-60.367 0-117.12 23.508-159.806 66.194s-66.194 99.439-66.194 159.806 23.508 117.12 66.194 159.806 99.439 66.194 159.806 66.194 117.12-23.508 159.806-66.194 66.194-99.439 66.194-159.806-23.508-117.12-66.194-159.806-99.439-66.194-159.806-66.194z"/></g><g><path d="m241 60.036h30v40.032h-30z"/></g><g><path d="m360.398 116.586h40.032v30h-40.032z" transform="matrix(.707 -.707 .707 .707 18.375 307.534)"/></g><g><path d="m411.932 241h40.032v30h-40.032z"/></g><g><path d="m365.414 360.398h30v40.032h-30z" transform="matrix(.707 -.707 .707 .707 -157.573 380.414)"/></g><g><path d="m241 411.932h30v40.032h-30z"/></g><g><path d="m111.57 365.414h40.032v30h-40.032z" transform="matrix(.707 -.707 .707 .707 -230.453 204.466)"/></g><g><path d="m60.036 241h40.032v30h-40.032z"/></g><g><path d="m116.586 111.57h30v40.032h-30z" transform="matrix(.707 -.707 .707 .707 -54.505 131.586)"/></g><g><path d="m361.892 271h-120.892v-120.892h30v90.892h90.892z"/></g></g></svg>
							<?= $collector->showDate($data->created_at) ?>
						</div>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
	
	</div>
</div>
`

**Comment by temirovgroup** [comment]
If disable concatJS, comment work.. 

when concatJS is disabled, the page does not reload when adding 2 comments.
Please excuse my English.

**Comment by rmrevin** [comment]
Please format your code. Or give read access to the repository.

**Comment by temirovgroup** [comment]
[1.zip](https://github.com/rmrevin/yii2-minify-view/files/5168217/1.zip)

this controller, model, view.

**Comment by temirovgroup** [comment]
``
	$("#comment-form").on("pjax:end", function() {
		$.pjax.reload({
			container: "#comment-list"
		});
		
		// Lozad
		myLozad(200);
	});
``

this js code reload comment-list

**Comment by rmrevin** [comment]
https://i.imgur.com/GijaBJE.png
Your handler will respond with a new minified script that specifically addresses this form. Make sure that the initialization of the script after loading is correct. But it is better to remove scripts from ajax transmission.

The script must be initialized on the page once and process any specific form.

**Comment by temirovgroup** [comment]
Thank You! I'll check it out.
