### ISSUE TITLE
External sources

### ISSUE THREAD

**Issue by RaSeR** [rmrevin/yii2-minify-view#8]
How can we handle external sources? Like jQuery with its //code.jquery.com/jquery-1.11.2.min.js or smth else.

**Comment by rmrevin** [comment]
We have added support for external javascript files in version 1.7.0
Thank U.

**Comment by RaSeR** [comment]
It will work for external css too?

**Comment by RaSeR** [comment]
As i can see, its not getting data from google/fonts css files((

**Comment by rmrevin** [comment]
For css we will add support later. You can insert a link to google fonts via `@import`. This method is processed without problems.

**Comment by RaSeR** [comment]
Ok
