### ISSUE TITLE
Option to avoid minify <pre> at all

### ISSUE THREAD

**Issue by RaSeR** [rmrevin/yii2-minify-view#9]
I have site which use a lot of "pre" elements and i do new lines by myself. Your minify add one more new line at the end, cause you don't use PHP_EOL and just put "\n", so now i have 2 new lines instead of just 1.

**Comment by rmrevin** [comment]
This refers to the class `HtmlCompressor`?

**Comment by rmrevin** [comment]
Not sure what to do. Please send pull request.

**Comment by RaSeR** [comment]
Yeap, its for HtmlCompressor. Ok, i'll try to fix it by myself and send you pull request, as soon as possible.

**Comment by rmrevin** [comment]
We have released a fix in last version. Can check.
